# -*- coding: utf-8 -*-
"""lab 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kG_DJcvIcyRUq3FRmGCGvl8GnNoHeqU6
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

student_data = pd.read_csv("student-mat.csv", sep=";")

student_data.head()

print("Shape:", student_data.shape)

student_data.columns

student_data.info()

student_data.describe()

print(student_data.isnull().sum())

print("Duplicate Rows:", student_data.duplicated().sum())

"""Conclusion of Task 1

The Student Performance dataset was successfully loaded and explored. The dataset contains 395 student records and 33 features. No missing values or duplicate records were found. After understanding the dataset structure, it is ready for preprocessing and feature engineering before training the Linear Regression model.

Task 2: Data Preprocessing
"""

print(student_data.isnull().sum())

print("Duplicate Rows:", student_data.duplicated().sum())

student_data.dtypes

student_data = pd.get_dummies(student_data, drop_first=True)

# Create input features
X = student_data.drop("G3", axis=1)

# Create target variable
y = student_data["G3"]

from sklearn.preprocessing import StandardScaler

# Create a StandardScaler object
scaler = StandardScaler()

# Scale all input features
X_scaled = scaler.fit_transform(X)

"""Task 3: Feature Selection"""

# Select all columns except the target variable (G3)
X = student_data.drop("G3", axis=1)

# Select the target variable
y = student_data["G3"]

# Display the dimensions of the feature matrix
print("Feature Shape:", X.shape)

# Display the dimensions of the target variable
print("Target Shape:", y.shape)

"""Task 4 – Train-Test Split,"""

from sklearn.model_selection import train_test_split

# Split the dataset into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

# Display the number of training samples

print("Training Samples:", X_train.shape[0])

# Display the number of testing samples

print("Testing Samples:", X_test.shape[0])

"""Task 5 – Linear Regression using Gradient Descent"""

import numpy as np

def gradient_descent(X, y, learning_rate=0.01, iterations=1000):

    # Number of training samples (m) and features (n)
    m, n = X.shape

    # Initialize weights with zeros
    weights = np.zeros(n)

    # Initialize bias
    bias = 0

    # Store the cost after each iteration
    cost_history = []

    # Perform Gradient Descent
    for i in range(iterations):

        # Step 1: Predict the output
        y_pred = np.dot(X, weights) + bias

        # Step 2: Calculate prediction error
        error = y_pred - y

        # Step 3: Compute gradients
        dw = (1 / m) * np.dot(X.T, error)
        db = (1 / m) * np.sum(error)

        # Step 4: Update weights and bias
        weights = weights - learning_rate * dw
        bias = bias - learning_rate * db

        # Step 5: Compute Mean Squared Error (Cost)
        cost = (1 / (2 * m)) * np.sum(error ** 2)

        # Store the cost
        cost_history.append(cost)

    return weights, bias, cost_history

# Train the Linear Regression model
weights, bias, cost_history = gradient_descent(
    X_train,
    y_train,
    learning_rate=0.01,
    iterations=1000
)

print("Bias:")
print(bias)

print("\nWeights:")
print(weights)

"""Task 6 – Effect of Learning Rate on Gradient Descent"""

# Define different learning rates
learning_rates = [0.001, 0.01, 0.1]

# Dictionary to store cost history for each learning rate
results = {}

# Train the model for each learning rate
for lr in learning_rates:

    weights, bias, cost_history = gradient_descent(
        X_train,
        y_train,
        learning_rate=lr,
        iterations=1000
    )

    # Store cost history
    results[lr] = cost_history

# Create a new figure
plt.figure(figsize=(8,5))

# Plot the cost curve for each learning rate
for lr in learning_rates:
    plt.plot(results[lr], label=f"Learning Rate = {lr}")

# Add labels and title
plt.xlabel("Iterations")
plt.ylabel("Cost (MSE)")
plt.title("Learning Rate vs Cost Convergence")

# Display legend and grid
plt.legend()
plt.grid(True)

# Show the graph
plt.show()

"""Conclusion

The convergence graph shows that different learning rates produce different optimization behaviors. A learning rate of 0.001 converges slowly due to small parameter updates, while 0.1 reaches the minimum cost much faster. The learning rate of 0.01 provides a balanced trade-off between convergence speed and stability. Selecting an appropriate learning rate is essential for efficient and accurate model training.

Task 7 – Model Evaluation
"""

# Train the model using the best learning rate

weights, bias, cost_history = gradient_descent(
    X_train,
    y_train,
    learning_rate=0.1,
    iterations=1000
)

# Predict the final grades for the testing dataset

y_pred = np.dot(X_test, weights) + bias

# Import regression evaluation metrics

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import numpy as np

# Calculate Mean Absolute Error

mae = mean_absolute_error(y_test, y_pred)

# Calculate Mean Squared Error

mse = mean_squared_error(y_test, y_pred)

# Calculate Root Mean Squared Error

rmse = np.sqrt(mse)

# Calculate R² Score

r2 = r2_score(y_test, y_pred)

# Display the evaluation metrics

print("Model Evaluation")
print("-----------------------")
print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R² Score:", r2)

"""Task 8 – Interpretation of Results"""

# Create a scatter plot of actual vs predicted grades

plt.figure(figsize=(6,6))

# Plot actual and predicted values
plt.scatter(y_test, y_pred)

# Plot the reference line (perfect prediction)
plt.plot([y.min(), y.max()],
         [y.min(), y.max()],
         'r--')

# Label the axes
plt.xlabel("Actual G3")
plt.ylabel("Predicted G3")

# Add title
plt.title("Actual vs Predicted Grades")

# Display grid
plt.grid(True)

# Show the graph
plt.show()

"""Overall Interpretation of Results

The Gradient Descent algorithm successfully minimized the cost function and converged during training. By comparing different learning rates, it was observed that:

A learning rate of 0.001 resulted in slow convergence due to very small parameter updates.
A learning rate of 0.01 provided smooth and stable convergence with a good balance between speed and accuracy.
A learning rate of 0.1 achieved the fastest stable convergence for this dataset.

The evaluation metrics indicate that the trained model performs well on the testing dataset:

Mean Absolute Error (MAE): 1.65 indicates that the model's predictions differ from the actual grades by approximately 1.65 marks on average.
Mean Squared Error (MSE): 5.66 shows that the average squared prediction error is relatively low.
Root Mean Squared Error (RMSE): 2.38 indicates that the prediction error is about 2.38 marks, which is acceptable considering the grading scale.
R² Score: 0.7241 means that the model explains approximately 72.4% of the variation in students' final grades, demonstrating good predictive performance.

The Actual vs Predicted scatter plot further confirms that the predictions closely match the actual values, as most points lie near the diagonal reference line.
"""