# -*- coding: utf-8 -*-
"""lab 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GaNgDxc0vJoY2EnoSoSBSP1YcirnIxu5

Step 1: Import the Required Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_breast_cancer

cancer = load_breast_cancer()

df = pd.DataFrame(
    cancer.data,
    columns=cancer.feature_names
)

df["Target"] = cancer.target

df.head()

print(df.shape)

df.info()

df.describe()

print(df.isnull().sum())

print(df.duplicated().sum())

print(df["Target"].value_counts())

sns.countplot(x="Target", data=df)

plt.title("Distribution of Target Classes")

plt.xlabel("Target (0 = Malignant, 1 = Benign)")

plt.ylabel("Count")

plt.show()

"""Task 2: Data Preprocessing"""

# Features (Independent Variables)
X = df.drop("Target", axis=1)

# Target (Dependent Variable)
y = df["Target"]

print("Feature Shape:", X.shape)

print("Target Shape:", y.shape)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

"""Why is Scaling Necessary?
Logistic Regression

Scaling is not strictly required, but it helps the optimization algorithm converge faster and more reliably.

KNN

Scaling is essential because KNN calculates distances between data points. If one feature has much larger values than others, it can dominate the distance calculation and reduce model performance.
"""

print(X_scaled[:5])

"""Task 3: Train-Test Split"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training Features:", X_train.shape)
print("Testing Features :", X_test.shape)

print("Training Labels :", y_train.shape)
print("Testing Labels  :", y_test.shape)

"""Task 4: Logistic Regression"""

from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression(random_state=42)

log_model.fit(X_train, y_train)

y_pred_log = log_model.predict(X_test)

print(y_pred_log[:10])

print("Actual Labels:")
print(y_test.values[:10])

print()

print("Predicted Labels:")
print(y_pred_log[:10])

"""Task 5: K-Nearest Neighbors (KNN)"""

from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=7)

knn_model.fit(X_train, y_train)

y_pred_knn = knn_model.predict(X_test)

print(y_pred_knn[:10])

print("Actual Labels:")
print(y_test.values[:10])

print()

print("Predicted Labels:")
print(y_pred_knn[:10])

"""Task 6: Model Evaluation"""

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    ConfusionMatrixDisplay,
    classification_report
)

log_accuracy = accuracy_score(y_test, y_pred_log)

print("Accuracy:", log_accuracy)

log_precision = precision_score(y_test, y_pred_log)

print("Precision:", log_precision)

log_recall = recall_score(y_test, y_pred_log)

print("Recall:", log_recall)

log_f1 = f1_score(y_test, y_pred_log)

print("F1 Score:", log_f1)

cm_log = confusion_matrix(y_test, y_pred_log)

print(cm_log)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_log,
    display_labels=["Malignant", "Benign"]
)

disp.plot(cmap="Blues")

plt.title("Logistic Regression - Confusion Matrix")

plt.grid(False)

plt.show()

"""Explanation

Instead of printing numbers, this code displays the confusion matrix as a colored graph.

Darker cells = More samples
Lighter cells = Fewer samples

This makes the results easier to interpret visually.
"""

print(classification_report(
    y_test,
    y_pred_log,
    target_names=["Malignant", "Benign"]
))

print("===== KNN =====")

knn_accuracy = accuracy_score(y_test, y_pred_knn)

knn_precision = precision_score(y_test, y_pred_knn)

knn_recall = recall_score(y_test, y_pred_knn)

knn_f1 = f1_score(y_test, y_pred_knn)

print("Accuracy :", knn_accuracy)

print("Precision:", knn_precision)

print("Recall :", knn_recall)

print("F1 Score :", knn_f1)

"""Task 7: Compare Logistic Regression and KNN"""

comparison = pd.DataFrame({
    "Metric": ["Accuracy", "Precision", "Recall", "F1 Score"],

    "Logistic Regression": [
        log_accuracy,
        log_precision,
        log_recall,
        log_f1
    ],

    "KNN": [
        knn_accuracy,
        knn_precision,
        knn_recall,
        knn_f1
    ]
})

comparison

comparison = comparison.round(4)

comparison

comparison.style.highlight_max(
    subset=["Logistic Regression", "KNN"],
    color="lightgreen"
)

"""Task 8: Interpretation

Interpretation

Both Logistic Regression and K-Nearest Neighbors (KNN) classifiers performed well on the Breast Cancer Wisconsin (Diagnostic) dataset.

The comparison of Accuracy, Precision, Recall, and F1 Score shows that both models can effectively classify breast cancer tumors.

However, Logistic Regression achieved:

Higher Accuracy
Higher Precision
Higher F1 Score

Both models obtained the same Recall.

The confusion matrices also showed that Logistic Regression made fewer incorrect predictions than KNN.

Therefore, Logistic Regression provided more consistent and reliable classification performance on this dataset.

The comparison showed that:

Logistic Regression Accuracy: 98.25%
KNN Accuracy: 96.49%
Logistic Regression achieved higher Precision and F1 Score.
Both models achieved the same Recall.

Hence, Logistic Regression is the better-performing classifier for this dataset, as it provides more accurate and consistent predictions than KNN.

This experiment demonstrates that choosing an appropriate machine learning model and evaluating it using multiple performance metrics is essential for selecting the most suitable classifier for a real-world problem.
"""