# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16vMs2bW3OFx439eGBvCs9Dmj1eySBaZf
"""

import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.naive_bayes import CategoricalNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

df = pd.read_csv("/content/datset.csv")

print(df)

"""This cell loads the `datset.csv` file into a pandas DataFrame named `df` and then prints the entire DataFrame to display its contents. We can see all 50 rows and 6 columns, including the 'No' column (an identifier), categorical features like 'Outlook', 'Temperature', 'Humidity', 'Wind', and the target variable 'Play Tennis'."""

print("First 5 Rows:")
print(df.head())

print("\nDataset Shape:")
print(df.shape)

print("\nDataset Information:")
print(df.info())

"""This cell provides an initial overview of the loaded dataset. It shows the first 5 rows of the DataFrame, confirms its shape (50 rows, 6 columns), and displays the data types for each column using `df.info()`. All feature columns and the target column are of `object` type, indicating they are categorical strings, while the 'No' column is an integer."""

plt.figure(figsize=(5,4))

sns.countplot(x='Play Tennis', data=df)

plt.title("Distribution of Play Tennis")
plt.xlabel("Play Tennis")
plt.ylabel("Count")

plt.show()

print("Null Values in Each Column:")
print(df.isnull().sum())

print("\nTotal Missing Values:", df.isnull().sum().sum())

"""This cell checks for any missing (null) values across all columns in the dataset. The output confirms that there are no null values in any of the columns, meaning the dataset is complete and does not require imputation for missing data."""

missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_df = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage (%)": missing_percentage
})

print("Missing Value Analysis:")
print(missing_df)

"""This cell elaborates on the missing value analysis by calculating and displaying the percentage of missing values for each column. As expected from the previous check, all columns show 0 missing values and 0% missing data, reinforcing that the dataset is clean in terms of completeness."""

print("Number of Duplicate Rows:", df.duplicated().sum())

# Uncomment the following line to remove duplicates if any
# df = df.drop_duplicates()

"""This cell checks for duplicate rows in the dataset. The output indicates that there are no duplicate rows, meaning each entry in the dataset is unique. This is good for model training as it prevents bias from repeated observations."""

print("Data Types:")
print(df.dtypes)

"""This cell explicitly prints the data types of all columns in the DataFrame. It reconfirms that 'No' is `int64` and all other columns ('Outlook', 'Temperature', 'Humidity', 'Wind', 'Play Tennis') are `object` type, which is consistent with their categorical nature and the need for encoding."""

for column in df.columns:
    print(f"\n{column}:")
    print(df[column].unique())

"""This cell displays all unique values for each column. This is crucial for understanding the distinct categories within each feature and the target variable. For example, 'Outlook' has 'Sunny', 'Overcast', 'Rain'; 'Temperature' has 'Hot', 'Mild', 'Cool'; and 'Play Tennis' has 'No', 'Yes'. This helps confirm the categorical nature of the data before encoding."""

# Features and target
X = df[['Outlook', 'Temperature', 'Humidity', 'Wind']]
y = df['Play Tennis']

# Encode features
feature_encoders = {}

for column in X.columns:
    le = LabelEncoder()
    X[column] = le.fit_transform(X[column])
    feature_encoders[column] = le

# Encode target
target_encoder = LabelEncoder()
y = target_encoder.fit_transform(y)

print("Encoded Features:")
print(X)

print("\nEncoded Target:")
print(y)

"""This cell performs the crucial data preprocessing step of converting categorical features and the target variable into numerical representations using `LabelEncoder`. It separates the features (`X`) from the target (`y`), then iterates through each feature column to encode it. Finally, it encodes the target variable. The output displays the encoded `X` DataFrame and the encoded `y` array, showing the numerical mapping of the original categorical values."""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training Samples:", len(X_train))
print("Testing Samples:", len(X_test))

"""This cell divides the preprocessed dataset into training and testing subsets using `train_test_split` with an 80:20 ratio. `random_state=42` ensures reproducibility, and `stratify=y` maintains the proportion of target classes in both subsets, which is important for imbalanced datasets. The output shows the number of samples allocated to the training and testing sets."""

nb = CategoricalNB()

nb.fit(X_train, y_train)

y_pred = nb.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report")
print(classification_report(
    y_test,
    y_pred,
    target_names=target_encoder.classes_
))

"""This cell evaluates the performance of the trained Categorical Naive Bayes model on the test set. It calculates and prints the overall accuracy, the confusion matrix (showing true positives, true negatives, false positives, false negatives), and a classification report (including precision, recall, and f1-score for each class and their averages). This gives a comprehensive view of how well the Naive Bayes model performed."""

sample = pd.DataFrame({
    'Outlook': ['Sunny'],
    'Temperature': ['Cool'],
    'Humidity': ['High'],
    'Wind': ['Strong']
})

for column in sample.columns:
    sample[column] = feature_encoders[column].transform(sample[column])

prediction = nb.predict(sample)
probability = nb.predict_proba(sample)

print("Predicted Class:",
      target_encoder.inverse_transform(prediction)[0])

print("\nClass Probabilities:")

for cls, prob in zip(target_encoder.classes_, probability[0]):
    print(f"{cls}: {prob:.4f}")

"""This cell performs a single-sample inference using the trained Categorical Naive Bayes model. It defines a new sample with specific weather conditions, encodes these conditions using the same encoders fitted during training, and then predicts the class label ('Play Tennis' or 'No Play Tennis') and the probability for each class. The output shows the predicted class ('No' in this case) and the corresponding probabilities, indicating the model's confidence in its prediction."""

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

dt_pred = dt.predict(X_test)

dt_acc = accuracy_score(y_test, dt_pred)

dt_sample = dt.predict(sample)

dt_prob = dt.predict_proba(sample)

print("Decision Tree Accuracy:", dt_acc)
print("Prediction:", target_encoder.inverse_transform(dt_sample)[0])
print("Probabilities:", dt_prob)

"""This cell trains a Decision Tree Classifier on the same training data and evaluates its performance. It calculates the accuracy on the test set and then performs a single-sample prediction for the same conditions used earlier. The output displays the Decision Tree's accuracy, its prediction for the sample, and the class probabilities, allowing for a direct comparison with the Naive Bayes model."""

lr = LogisticRegression(max_iter=1000)

lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)

lr_acc = accuracy_score(y_test, lr_pred)

lr_sample = lr.predict(sample)

lr_prob = lr.predict_proba(sample)

print("Logistic Regression Accuracy:", lr_acc)
print("Prediction:", target_encoder.inverse_transform(lr_sample)[0])
print("Probabilities:", lr_prob)

"""This cell trains a Logistic Regression model, evaluates its test set accuracy, and performs a single-sample inference. Similar to the previous models, it outputs the Logistic Regression model's accuracy, the predicted label for the specific sample, and the associated class probabilities. This adds another model to our comparison."""

svm = SVC(probability=True, random_state=42)

svm.fit(X_train, y_train)

svm_pred = svm.predict(X_test)

svm_acc = accuracy_score(y_test, svm_pred)

svm_sample = svm.predict(sample)

svm_prob = svm.predict_proba(sample)

print("SVM Accuracy:", svm_acc)
print("Prediction:", target_encoder.inverse_transform(svm_sample)[0])
print("Probabilities:", svm_prob)

"""This cell trains a Support Vector Machine (SVM) classifier with probability enabled, evaluates its accuracy on the test set, and performs a single-sample prediction. The output includes the SVM model's accuracy, the predicted class for the sample, and the class probabilities. This completes the training and individual evaluation of all four requested models."""

models = [
    "Naive Bayes",
    "Decision Tree",
    "Logistic Regression",
    "SVM"
]

accuracies = [
    accuracy,
    dt_acc,
    lr_acc,
    svm_acc
]

plt.figure(figsize=(8,5))

sns.barplot(
    x=models,
    y=accuracies
)

plt.ylim(0,1)

plt.ylabel("Accuracy")
plt.title("Model Accuracy Comparison")

for i,v in enumerate(accuracies):
    plt.text(i, v+0.02, f"{v:.2f}", ha='center')

plt.show()

print("="*80)
print("{:<25} {:<12} {:<15} {}".format(
    "Model",
    "Accuracy",
    "Prediction",
    "Class Probabilities"
))
print("="*80)

print("{:<25} {:<12.2f} {:<15} {}".format(
    "Categorical Naive Bayes",
    accuracy,
    target_encoder.inverse_transform(prediction)[0],
    probability[0]
))

print("{:<25} {:<12.2f} {:<15} {}".format(
    "Decision Tree",
    dt_acc,
    target_encoder.inverse_transform(dt_sample)[0],
    dt_prob[0]
))

print("{:<25} {:<12.2f} {:<15} {}".format(
    "Logistic Regression",
    lr_acc,
    target_encoder.inverse_transform(lr_sample)[0],
    lr_prob[0]
))

print("{:<25} {:<12.2f} {:<15} {}".format(
    "SVM",
    svm_acc,
    target_encoder.inverse_transform(svm_sample)[0],
    svm_prob[0]
))

"""This cell provides a clear, formatted comparison table summarizing the performance of all four classification models: Categorical Naive Bayes, Decision Tree, Logistic Regression, and SVM. For each model, it displays the test accuracy, the predicted outcome for the single-sample query, and the corresponding class probabilities. This table allows for an easy side-by-side assessment of how each model performs on both the overall test data and a specific prediction scenario."""

classes = target_encoder.classes_
prob = probability[0]

plt.figure(figsize=(5,4))

plt.bar(classes, prob)

plt.title("Naive Bayes Prediction Probability")
plt.xlabel("Class")
plt.ylabel("Probability")

plt.ylim(0,1)

plt.show()