# -*- coding: utf-8 -*-
"""lab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13J6I6sWqhFqoI2wsAEEJNTmGJz0790xe
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler

"""Task 1:"""

data = load_breast_cancer()

print(data.keys())

df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target

df.head()

print("Shape:", df.shape)

print(df.columns)

df.info()

df.isnull().sum()

print("Duplicate rows:", df.duplicated().sum())

"""Target distribution"""

print(df['target'].value_counts())

sns.countplot(x='target', data=df)
plt.title("Target Distribution")
plt.show()

"""Feature Scaling"""

X = df.drop('target', axis=1)
y = df['target']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print(X_scaled[:5])

"""Task 2

"""

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

def evaluate_split(test_size):
    # Split dataset
    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=test_size,
        random_state=42,
        stratify=y
    )

    # Scale after split
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # Temporary K for Task 2
    knn = KNeighborsClassifier(n_neighbors=5)
    knn.fit(X_train_scaled, y_train)

    y_pred = knn.predict(X_test_scaled)
    accuracy = accuracy_score(y_test, y_pred)

    return len(X_train), len(X_test), accuracy

splits = [0.2, 0.3, 0.1]

for split in splits:
    train_size, test_size, acc = evaluate_split(split)

    print(f"Split {(1-split)*100:.0f}:{split*100:.0f}")
    print(f"Training Samples: {train_size}")
    print(f"Testing Samples: {test_size}")
    print(f"Accuracy: {acc:.4f}")
    print()

splits = ['80:20', '70:30', '90:10']
accuracies = [95.61, 95.91, 98.25]

plt.figure(figsize=(7,5))
plt.bar(splits, accuracies)
plt.xlabel("Train-Test Split")
plt.ylabel("Accuracy (%)")
plt.title("Accuracy Comparison Across Different Splits")
plt.ylim(90, 100)
plt.grid(axis='y')
plt.show()

"""Task 3

model train using heuristic k
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""Evaluating multiple value of k"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

k_values = range(1, 31)
accuracies = []

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_scaled, y_train)

    y_pred = knn.predict(X_test_scaled)
    acc = accuracy_score(y_test, y_pred)
    accuracies.append(acc)

plt.figure(figsize=(8,5))
plt.plot(k_values, accuracies, marker='o')
plt.axvline(x=21, linestyle='--', label='Heuristic K = 21')

plt.xlabel("K Value")
plt.ylabel("Accuracy")
plt.title("Accuracy vs K")
plt.grid(True)
plt.legend()
plt.show()

"""best k"""

best_k = k_values[np.argmax(accuracies)]
best_accuracy = max(accuracies)

print("Best K:", best_k)
print("Best Accuracy:", best_accuracy)

"""Apply pca

"""

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

print(X_pca.shape)

from sklearn.model_selection import train_test_split

X_train_pca, X_test_pca, y_train_pca, y_test_pca = train_test_split(
    X_pca, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier

def plot_decision_boundary(k):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_pca, y_train_pca)

    x_min, x_max = X_pca[:, 0].min() - 1, X_pca[:, 0].max() + 1
    y_min, y_max = X_pca[:, 1].min() - 1, X_pca[:, 1].max() + 1

    xx, yy = np.meshgrid(
        np.linspace(x_min, x_max, 300),
        np.linspace(y_min, y_max, 300)
    )

    Z = knn.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)

    plt.figure(figsize=(7,5))
    plt.contourf(xx, yy, Z, alpha=0.3)
    plt.scatter(
        X_train_pca[:, 0],
        X_train_pca[:, 1],
        c=y_train_pca,
        edgecolor='k',
        s=25
    )

    plt.title(f"Decision Boundary (K={k})")
    plt.xlabel("Principal Component 1")
    plt.ylabel("Principal Component 2")
    plt.show()

plot_decision_boundary(1)
plot_decision_boundary(5)
plot_decision_boundary(10)
plot_decision_boundary(20)

"""Task 4"""

from sklearn.model_selection import cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
import numpy as np

k_values = range(1, 31)
cv_scores = []

for k in k_values:
    pipeline = Pipeline([
        ('scaler', StandardScaler()),
        ('knn', KNeighborsClassifier(n_neighbors=k))
    ])

    scores = cross_val_score(
        pipeline,
        X,
        y,
        cv=5,
        scoring='accuracy'
    )

    cv_scores.append(scores.mean())

plt.figure(figsize=(8,5))
plt.plot(k_values, cv_scores, marker='o')

plt.xlabel("K Value")
plt.ylabel("Mean Cross Validation Accuracy")
plt.title("5-Fold Cross Validation Accuracy vs K")
plt.grid(True)
plt.show()

best_cv_k = k_values[np.argmax(cv_scores)]
best_cv_score = max(cv_scores)

print("Best K from CV:", best_cv_k)
print("Best Mean Accuracy:", best_cv_score)

"""Predictions"""

from sklearn.neighbors import KNeighborsClassifier

final_knn = KNeighborsClassifier(n_neighbors=7)
final_knn.fit(X_train_scaled, y_train)

y_pred = final_knn.predict(X_test_scaled)

print(y_pred[:20])

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Final Model Accuracy:", accuracy)

sample = X.iloc[[542]]
print(sample)

sample_scaled = scaler.transform(sample)

prediction = final_knn.predict(sample_scaled)
print(prediction)

if prediction[0] == 0:
    print("Predicted: Malignant")
else:
    print("Predicted: Benign")

"""Task 5

"""

from sklearn.neighbors import KNeighborsClassifier

final_knn = KNeighborsClassifier(n_neighbors=7)
final_knn.fit(X_train_scaled, y_train)

y_pred = final_knn.predict(X_test_scaled)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred)
print("Precision:", precision)

from sklearn.metrics import recall_score

recall = recall_score(y_test, y_pred)
print("Recall:", recall)

from sklearn.metrics import f1_score

f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=data.target_names
)

disp.plot(cmap="Blues")
plt.title("Confusion Matrix")
plt.grid(False)
plt.show()

from sklearn.metrics import classification_report

print(classification_report(
    y_test,
    y_pred,
    target_names=["Malignant", "Benign"]
))

y_prob = final_knn.predict_proba(X_test_scaled)[:, 1]

from sklearn.metrics import roc_curve, auc

fpr, tpr, thresholds = roc_curve(y_test, y_prob)
roc_auc = auc(fpr, tpr)

print("AUC Score:", roc_auc)

plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.3f}")
plt.plot([0,1], [0,1], linestyle='--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.grid(True)
plt.show()

"""Task 6: Comparative Study with Regression

# Task 6: Comparative Study with Regression (Lab 3 Integration)

## Comparison of Regression and Classification Metrics
Regression and classification use different evaluation metrics because their outputs are different. Regression predicts continuous numerical values, so metrics like **MAE, MSE, RMSE, and R²** are used to measure prediction error. Classification predicts categories or classes, so metrics like **Accuracy, Precision, Recall, F1 Score, and Confusion Matrix** are used to measure decision correctness.

---

## Error-Based Evaluation (Regression)
Regression evaluation is error-based because the predicted value can differ from the actual value by some amount. Metrics such as **MAE, MSE, and RMSE** measure how large this prediction error is.

**Example:**  
Actual GPA = 3.5  
Predicted GPA = 3.2  
Error = 0.3  

---

## Decision-Based Evaluation (Classification)
Classification evaluation is decision-based because the output is a class label. The prediction is either correct or incorrect. Metrics like **Accuracy, Precision, Recall, and F1 Score** evaluate how well the model classifies data.

**Example:**  
Actual = Malignant  
Predicted = Benign → Wrong classification  

---

## R² Score vs Accuracy
- **R² Score** measures how well a regression model explains variation in data. Higher R² means better prediction of numerical values.  
- **Accuracy** measures the percentage of correct classifications. Higher accuracy means better classification performance.

---

## RMSE vs F1 Score
- **RMSE** measures the average magnitude of prediction error in regression. Lower RMSE is better.  
- **F1 Score** balances precision and recall in classification. Higher F1 score indicates better overall classification performance.

---

## MAE vs Confusion Matrix
- **MAE** gives the average absolute error between actual and predicted numerical values.  
- **Confusion Matrix** shows the number of correct and incorrect classifications (**TP, TN, FP, FN**).

---

## Continuous Prediction vs Classification
- **Continuous Prediction Tasks (Regression):** Output is numerical, such as GPA, salary, or house price. Evaluation focuses on prediction error.  
- **Classification Tasks:** Output is categorical, such as benign/malignant or spam/not spam. Evaluation focuses on correct decision-making.

---

## Inference
Regression metrics measure **how far predictions are from actual values**, while classification metrics measure **how correctly the model makes decisions**. Regression focuses on error magnitude, whereas classification focuses on prediction correctness.

# Task 7: Analytical Questions

## 1. Why is KNN called a lazy learning algorithm?
KNN is called a lazy learning algorithm because it does not build a model during training. It simply stores the training data and performs computation only when a new data point needs to be classified.

---

## 2. Why is feature scaling required in KNN?
Feature scaling is required because KNN is a distance-based algorithm. Features with larger numerical values can dominate distance calculations and bias the prediction. Scaling ensures all features contribute equally.

---

## 3. Explain heuristic K selection using √n rule.
A common heuristic for choosing K is:

\[
K = \sqrt{n}
\]

where **n** is the number of training samples. This provides a reasonable starting value for K, which can later be optimized using validation methods.

---

## 4. Why is cross-validation more reliable than a single train-test split?
Cross-validation is more reliable because it evaluates the model on multiple train-test splits instead of just one. This reduces dependence on a single random split and provides a better estimate of model generalization.

---

## 5. How does K affect bias-variance trade-off?
Small K values lead to low bias but high variance, which may cause overfitting. Large K values lead to high bias but low variance, which may cause underfitting. Choosing the right K balances bias and variance.

---

## 6. Why is recall more important than accuracy in cancer prediction?
Recall is more important because it measures how many actual cancer cases are correctly identified. Missing a cancer case (false negative) can delay treatment and be dangerous, even if overall accuracy is high.

---

## 7. What is the limitation of very large K values?
Very large K values make the model consider too many neighbors, including distant points. This can oversmooth decision boundaries and lead to underfitting, reducing classification performance.
"""