# -*- coding: utf-8 -*-
"""ml lab 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dCY-0U9QjDxTnd0miVrtmd2S4D6tooxX
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

city = pd.read_csv("city_day.csv")
crop = pd.read_csv("crop_production.csv")

print("City Dataset Shape:", city.shape)
print("Crop Dataset Shape:", crop.shape)

city.head()

crop.head()

city.columns

crop.columns

city.info()

crop.info()

city.describe()

crop.describe()

city.isnull().sum()

crop.isnull().sum()

city.duplicated().sum()

crop.duplicated().sum()

"""## Data sheet
- **city_day.csv**

- **Number of rows:** 29531
- **Number of columns:** 15 (after dropping 'Xylene')
- **Key columns:** 'City', 'Date', 'AQI'
- **Missing values:** All missing values were imputed (numeric with median, 'AQI_Bucket' with mode).
- **Duplicate records:** 0

## Problem (city_day.csv):
Xylene contains a very high number of missing values which may reduce data quality.


- **crop_production.csv**

- **Number of rows:** 246091
- **Number of columns:** 7
- **Key columns:** 'State_Name', 'Crop_Year', 'Crop', 'Production'
- **Missing values:** 'Production' had 3730 missing values, which were imputed with the median.
- **Duplicate records:** 0

## Problem (crop_production.csv):
The 'Production' column had missing values which needed imputation.

***task 2***
"""

print("CITY DATASET")
print(city.isnull().sum())

print("\nCROP DATASET")
print(crop.isnull().sum())

"""new for me"""

(city.isnull().sum()/len(city))*100

"""### Task 2: Missing Value Treatment Strategy Justification

**Strategy for `city` dataset:**

1.  **`Xylene` column:** This column has a very high percentage of missing values (61.32%). Imputing such a large proportion of data could introduce significant bias and distort the underlying distribution. Therefore, we **dropped** this column to maintain data integrity.
2.  **Other numerical columns (`PM2.5`, `PM10`, `NO`, `NO2`, `NOx`, `NH3`, `CO`, `SO2`, `O3`, `Benzene`, `Toluene`, `AQI`):** These columns contain varying but significant numbers of missing values. We chose to **impute** these missing values with the **median** of their respective columns. The median is robust to outliers and is a suitable choice for skewed distributions, which is common for pollution data. This approach retains all rows of data while providing reasonable estimates for the missing sensor readings.
3.  **`AQI_Bucket` column:** This is a categorical column. We chose to **impute** missing values with the **mode** (most frequent value) of the column. This is a standard practice for handling missing categorical data, as it assigns the most probable category.

**Strategy for `crop` dataset:**

1.  **`Production` column:** This is a numerical column with 3730 missing values (1.5% of the total). We chose to **impute** these missing values with the **median** of the column. This approach is preferred over dropping rows, as it retains valuable information from the other columns, and the median is robust to any potential outliers in production figures.
"""

city.drop('Xylene', axis=1, inplace=True)

numeric_cols = city.select_dtypes(include=np.number).columns

for col in numeric_cols:
    city[col].fillna(city[col].median(), inplace=True)

city['AQI_Bucket'].fillna(
    city['AQI_Bucket'].mode()[0],
    inplace=True
)

crop['Production'].fillna(
    crop['Production'].median(),
    inplace=True
)

city.isnull().sum()

crop.isnull().sum()

"""Task 3:"""

crop['State_Name'].unique()

crop['State_Name'] = crop['State_Name'].str.strip()

crop['State_Name'] = crop['State_Name'].str.title()

before_crop = len(crop)
before_city = len(city)

print(before_crop)
print(before_city)

crop = crop.drop_duplicates()

city = city.drop_duplicates()

after_crop = len(crop)
after_city = len(city)

print(after_crop)
print(after_city)

"""Inconsistencies Found:

1. Leading/trailing spaces removed.
2. State names converted to title case.
3. Old state names standardized.

Duplicates:
Crop dataset:
Before = 246091
After = 246091

City dataset:
Before = 29531
After = 29531

Task 4:
"""

plt.figure(figsize=(10,5))

sns.histplot(city['AQI'], bins=30)

plt.title("Distribution of AQI Values")
plt.xlabel("AQI")
plt.ylabel("Frequency")

plt.show()

plt.figure(figsize=(10,3))

sns.boxplot(x=city['AQI'])

plt.title("Boxplot of AQI")

plt.show()

print("Mean AQI:", city['AQI'].mean())
print("Median AQI:", city['AQI'].median())

"""Justification:

Histogram shows where AQI values are concentrated.
Boxplot identifies extreme values and skewness.

Observations:

1. Most AQI values lie between approximately 50 and 250.
2. Several high AQI values create a long right tail, making the mean larger than the median.

Task 5
"""

plt.figure(figsize=(10,3))

sns.boxplot(x=city['AQI'])

plt.title("AQI Before Outlier Treatment")

plt.show()

Q1 = city['AQI'].quantile(0.25)
Q3 = city['AQI'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5*IQR
upper = Q3 + 1.5*IQR

print("Lower Bound:", lower)
print("Upper Bound:", upper)

outliers = city[
    (city['AQI'] < lower) |
    (city['AQI'] > upper)
]

print("Number of Outliers:", len(outliers))

city['AQI_clean'] = city['AQI'].clip(
    lower=lower,
    upper=upper
)

fig, ax = plt.subplots(1,2, figsize=(12,4))

sns.boxplot(x=city['AQI'], ax=ax[0])
ax[0].set_title("Before")

sns.boxplot(x=city['AQI_clean'], ax=ax[1])
ax[1].set_title("After")

plt.show()

"""Outlier Detection Method:
IQR method was used because AQI data is skewed.

Number of Outliers:
3192

Treatment:
Winsorization (capping) was applied.

Reason:
Extreme AQI values may be genuine observations. Capping reduces their influence while preserving all records.

Result:
The boxplot after treatment shows reduced impact of extreme values.

**Task 6: Is India's air getting better or worse**
"""

city['Date'] = pd.to_datetime(city['Date'])

city['Date'].head()

city['Year'] = city['Date'].dt.year

yearly_aqi = city.groupby('Year')['AQI'].mean().reset_index()

yearly_aqi

best_year = yearly_aqi.loc[yearly_aqi['AQI'].idxmin()]

worst_year = yearly_aqi.loc[yearly_aqi['AQI'].idxmax()]

print(best_year)
print(worst_year)

plt.figure(figsize=(10,5))

plt.plot(
    yearly_aqi['Year'],
    yearly_aqi['AQI'],
    marker='o'
)

plt.title('Average AQI by Year')
plt.xlabel('Year')
plt.ylabel('Average AQI')

plt.grid(True)

plt.show()

"""The data suggests that air quality has **improved** over the observed period. The most polluted year was **2015** with an average AQI of **179.62**, while the least polluted year was **2020** with an average AQI of **113.74**. The trend indicates that pollution levels have generally **decreased** over time, although some year-to-year fluctuations remain.

Task 7: Seasonal Pattern
"""

city['Month'] = city['Date'].dt.month

monthly_aqi = city.groupby('Month')['AQI'].mean().reset_index()

monthly_aqi

month_names = [
    'Jan','Feb','Mar','Apr','May','Jun',
    'Jul','Aug','Sep','Oct','Nov','Dec'
]
monthly_aqi['Month_Name'] = month_names

plt.figure(figsize=(10,5))

sns.lineplot(
    data=monthly_aqi,
    x='Month_Name',
    y='AQI',
    marker='o'
)

plt.title('Average AQI by Month')
plt.xlabel('Month')
plt.ylabel('Average AQI')

plt.show()

"""The analysis shows that AQI is highest during **October-December** months. October–December records an average AQI of **205.07** (average of 176.94 + 226.79 + 211.47), which is **higher** than the yearly average (158.78). Therefore, the NGO's claim that air quality is consistently worst during the October–December harvest season **is supported** by the data.

Task 8: Can the Two Datasets Talk to Each Other
"""

cities = sorted(city['City'].unique())

print("Number of unique cities:", len(cities))
print(cities)

# City -> State mapping

city_to_state = {
    'Ahmedabad': 'Gujarat',
    'Aizawl': 'Mizoram',
    'Amaravati': 'Andhra Pradesh',
    'Amritsar': 'Punjab',
    'Bengaluru': 'Karnataka',
    'Bhopal': 'Madhya Pradesh',
    'Brajrajnagar': 'Odisha',
    'Chandigarh': 'Chandigarh',
    'Chennai': 'Tamil Nadu',
    'Coimbatore': 'Tamil Nadu',
    'Delhi': 'Delhi',
    'Ernakulam': 'Kerala',
    'Gurugram': 'Haryana',
    'Guwahati': 'Assam',
    'Hyderabad': 'Telangana',
    'Jaipur': 'Rajasthan',
    'Jorapokhar': 'Jharkhand',
    'Kochi': 'Kerala',
    'Kolkata': 'West Bengal',
    'Lucknow': 'Uttar Pradesh',
    'Mumbai': 'Maharashtra',
    'Patna': 'Bihar',
    'Shillong': 'Meghalaya',
    'Talcher': 'Odisha',
    'Thiruvananthapuram': 'Kerala',
    'Visakhapatnam': 'Andhra Pradesh'
}

# Create State column
city['State'] = city['City'].map(city_to_state)

# Verify mapping worked
print("Missing states:", city['State'].isnull().sum())

# Show sample
city[['City', 'State']].head()

state_aqi_avg = (
    city.groupby('State')['AQI']
    .mean()
    .reset_index()
)

state_aqi_avg.head()

crop_state = (
    crop.groupby(['State_Name', 'Crop_Year'])
    .agg({
        'Area': 'sum',
        'Production': 'sum'
    })
    .reset_index()
)

crop_state.head(2)

state_aqi_avg = (
    city.groupby('State')['AQI']
    .mean()
    .reset_index()
)

state_aqi_avg.head()

state_aqi_avg['State'] = (
    state_aqi_avg['State']
    .str.strip()
    .str.title()
)

crop_state['State_Name'] = (
    crop_state['State_Name']
    .str.strip()
    .str.title()
)

merged = pd.merge(
    state_aqi_avg,
    crop_state,
    left_on='State',
    right_on='State_Name',
    how='inner'
)

print("Merged Shape:", merged.shape)

merged.head()

plt.figure(figsize=(8,6))

corr_matrix = merged.select_dtypes(include='number').corr()

sns.heatmap(
    corr_matrix,
    annot=True,
    cmap='coolwarm'
)

plt.title('Correlation Matrix of AQI, Area and Production')

plt.show()

merged[['AQI','Area','Production']].corr()

sns.pairplot(
    merged[['AQI','Area','Production']]
)

plt.show()

"""The AQI dataset was recorded at the city-day level, while the crop dataset was recorded at the state-year level. Because the time periods did not align well, both datasets were aggregated to the state level. Average AQI was calculated for each state, while total crop area and production were calculated for each state. The datasets were then merged using the state name, allowing exploratory analysis of relationships between air quality and agricultural output.

task 9 :-

The AQI dataset was recorded at the city-day level while the crop dataset was recorded at the state level. To make the datasets compatible, cities were mapped to their respective states. AQI values were then averaged for each state, while crop area and production were aggregated at the state level. After standardising state names, the datasets were merged using the State field.

Area and Production show a strong positive correlation. States with larger cultivated areas generally produce more crops because more land is available for farming.

AQI and Production show a weak negative correlation. This suggests states with poorer air quality may produce slightly less crop output. However, the relationship is weak and other factors such as rainfall, irrigation, soil quality and farming practices are likely to have a much larger influence.

extra some part of A
"""

highest = merged.loc[
    merged['AQI'].idxmax()
]

lowest = merged.loc[
    merged['AQI'].idxmin()
]

print(highest)
print("---------------------------------")
print(lowest)

corr_value = merged['AQI'].corr(
    merged['Production']
)

print(
    "Correlation between AQI and Production:",
    corr_value
)

"""The correlation coefficient between AQI and crop production is -0.216 This indicates a weak relationship. However, correlation does not prove causation.

### Task 9: Briefing for the Minister

**To the Honorable Minister,**

Our analysis of air quality and agricultural data in India reveals several key insights for your consideration.

**Findings:**

1.  **Air Quality Improvement:** India's overall air quality appears to be improving. The average Air Quality Index (AQI) has generally decreased from 2015 to 2020, with 2020 showing the lowest average AQI. This suggests that current environmental policies may be having a positive effect.
2.  **Seasonal Pollution Peaks:** Air pollution is consistently worst during the October-December period, aligning with claims about crop residue burning. This harvest season consistently records significantly higher AQI values compared to other months.
3.  **Weak Link to Crop Production:** We found a very weak negative relationship between average state-level air quality and crop production. States with slightly poorer air quality might have a marginally lower crop output, but this connection is not strong. Factors like rainfall, irrigation, and soil quality likely play a much larger role.

**Recommendation:**

Focus efforts on mitigating air pollution during the October-December harvest season through targeted initiatives to manage agricultural waste, potentially by promoting alternative uses for crop residue or supporting farmers in adopting less polluting practices.

**Limitation:**

While our data shows a correlation, it does not definitively prove that poor air quality *causes* a reduction in crop yields. Many other agricultural and environmental factors influence crop production, and further dedicated studies would be needed to establish a direct cause-and-effect relationship.
"""